title: Dr. Jekyll & Mr. Hyde git hub pages
theme: minima
author: GItHub @OccupyMars2077
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my test website's site description. This is helpful for Google searchs and SEO.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
